### PR TITLE
Upgraded to Angular v13

### PR DESCRIPTION
**Pull request by mdudek**

### CODE REVIEW

**Comment by meraj-ahmed** [comment]
@linnenschmidt  Is it possible to get this merged please? I am using angular 13 now, and it would help tremendously to be able to continue to use this package.

**Comment by iursevla** [comment]
@meraj-ahmed This lib doens't seem to be updated 
We might have to create a new lib forked from this and add it to npm.

I was going to implement the needed changes to use in angular 13 when i had the idea to come here to the pull requests tab.

Maybe @linnenschmidt  doesn't have the time for it right now. I had much much smaller libs and didn't have time to update in the past


@linnenschmidt can you add someone else to the project so that it can merge things? Thanks for your work 💯

**Comment by iursevla** [comment]
@mdudek noticed that you didn't change the tests directory. Maybe this is important to test that it works with Angular 13. FIles at https://github.com/linnenschmidt/build-ng-packagr/tree/master/tests/build_ng_packagr/ng-packaged 

I assume we only need to change https://github.com/linnenschmidt/build-ng-packagr/blob/master/tests/build_ng_packagr/ng-packaged/projects/lib/package.json

```ts
"peerDependencies": {
    "@angular/common": "^7.0.0-rc.0 || ^7.0.0",
    "@angular/core": "^7.0.0-rc.0 || ^7.0.0"
  }
```

to something like

```ts
"peerDependencies": {
    "@angular/common": "^7.0.0-rc.0 || ^13.0.0",
    "@angular/core": "^7.0.0-rc.0 || ^13.0.0"
}
```

---

Run the tests and can confirm that it fails. Seems to be related with the globby update to version 12.XX (See https://github.com/sindresorhus/globby/issues/193)

**Comment by meraj-ahmed** [comment]
@iursevla Thanks for the response. I ended up just implementing [ng-packagr](https://github.com/ng-packagr/ng-packagr) instead, which now supports copying static assets.

**Comment by iursevla** [comment]
@meraj-ahmed ah I see 
In my case I'm copying static assets but expecting to rename the directories (e.g. from A/ to dist/C). Do you know if ng-packagr supports that?

**Comment by iursevla** [comment]
@mdudek for the time being using your changes (did a fork from your pull request) plus some minor updates (mostly versions of packages) I have it working for Angular 13 on my company's library

Here's the npm package: https://www.npmjs.com/package/@iursevla/build-ng-packagr

The Github page is: https://github.com/iursevla/build-ng-packagr

**Pull request closed without merging**
